VAL_RATIO: float = 0.1
NUM_EPOCHS: int = 5

CLS_TARGET_NAME: str = 'is_safe'

CLS_EMBEDDING_DIM: int = 100
CLS_HIDDEN_DIM: int = 128
CLS_LR: float = 1e-3
CLS_MAX_LENGTH: int = 128

TRANSFORMATION_EMBEDDING_DIM: int = 128
TRANSFORMATION_HIDDEN_DIM: int = 512
TRANSFORMATION_LR: float = 3e-4
TRANSFORMATION_MAX_LENGTH: int = 512
TRANSFORMATION_NUM_HEADS: int = 4
TRANSFORMATION_NUM_LAYERS: int = 3
